Heroineeee/FE

- src/api/axiosInstance.ts
**axiosInstance 및 로그인 관련 API 파일 생성**
- src/api/axiosInstance.ts: 공통 Axios 인스턴스를 설정하는 파일을 생성
- src/api/auth.ts: 로그인 관련 API 요청을 정리한 파일을 생성
> feat(SCRUM-58): axiosInstance 생성

- src/api/user.ts
- src/pages/auth/NicknamePage.tsx
짧은 수정입니다...ㅎ
api 요청 방식을 PATCH로 착각했어영
닉네임 등록 api 요청은 POST!
> fix(SCRUM-6): 닉네임 등록 API POST 요청으로 수정하여 동작 오류 해결

- src/components/StoreSearch/StoreItem.tsx
- src/components/common/BottomSheet.tsx
- src/components/common/BottomSheetForm.tsx
- src/components/common/LoginRequiredBottomSheet.tsx
- src/components/common/SearchInput.tsx
- src/components/home/HomeTopBar.tsx
- src/pages/StoreSearch/StoreSearchPage.tsx
- src/pages/home/HomePage.tsx
• 로그인 요청 바텀 시트 구현
• 가맹점 스크랩 / 삭제 백엔드 API 연동
• 홈페이지 메뉴바 연결
> feat(SCRUM-75): 가맹점 스크랩 / 삭제 백엔드 API 연동

- package-lock.json
- package.json
- src/components/StoreDetail/BusinessHours.tsx
- src/components/StoreDetail/RequestEditButton.tsx
- src/components/StoreDetail/StoreDetailInfo.tsx
- src/components/common/BottomSheetForm.tsx
- src/pages/StoreDetail/StoreDetailPage.tsx
- src/pages/StoreSearch/StoreSearchPage.tsx
- src/types/store.ts
> Feat/scrum 63/store detail api

- src/components/StoreMap/StoreMap.tsx
- src/components/common/KakaoMap.tsx
• 가맹점 지도 페이지 지도 렌더링 및 마커 표시 (리스트에 따른)
> feat(SCRUM-129): 지도 렌더링 및 마커 표시

- src/components/StoreDetail/StoreDetailMap.tsx
- src/components/StoreMap/StoreMap.tsx
- src/components/common/KakaoMap.tsx
- src/contexts/KakaoMapContext.ts
- src/pages/store-map/StoreMapPage.tsx
• 로드된 new 데이터 마커 표시 (그 외의 데이터는 도트 마커 표시)
• 지도 중심 좌표 변경이 일정 임계값 이상일 때만 API 요청 (0.01)
• 마커 클릭 이벤트 처리 (해당 가맹점만 리스트에 표시)
• 마커 / 도트 마커 분리
> feat(SCRUM-129): 가맹점 지도 마커 표시 구현

- src/hooks/useBottomSheet.ts
- src/pages/store-map/StoreMapPage.tsx
- src/pages/store-search/StoreSearchPage.tsx
- tailwind.config.ts
• 가맹점 찾기 페이지 mt -> pt 수정
• 바텀 시트 영역 높이 수정 (아래로 내렸을 때)
• 가맹점 찾기 페이지 무한스크롤 오류 수정
• 가맹점 찾기 페이지 그림자 수정 (boxshadow custom 추가 - bottom)
> design: css 수정

- src/components/StoreMap/StoreMap.tsx
- src/hooks/useStoreSearch.ts
- src/pages/store-map/StoreMapPage.tsx
- src/pages/store-search/StoreSearchPage.tsx
• 지도 줌 레벨에 따른 마커 표시 구현
• 마커 + 가맹점 이름 표시 UI 수정
• 검색 필터링 오류 수정 (지역 검색 => keyword 파라미터 제외)
> feat(SCRUM-157): 지도 줌 레벨에 따른 마커 표시 구현

- src/components/StoreMap/StoreMap.tsx
- src/components/home/HeaderToCarouselSection.tsx
- src/hooks/useStoreSearch.ts
- src/pages/store-map/StoreMapPage.tsx
- src/pages/store-search/StoreSearchPage.tsx
• 메인페이지 검색 기능 구현 (지도 페이지 / 상세 페이지 이동)
• 지도 페이지 검색 기능 오류 수정
> feat(SCRUM-113): 메인페이지 검색 & GPS 기능 구현

- src/components/common/SearchInput.tsx
• 메인페이지 검색 예시 문구가 잘린 현상 css 수정
> fix: SearchInput 잘림 현상 수정

- src/components/StoreSearch/StoreList.tsx
- src/components/home/HeaderToCarouselSection.tsx
- src/components/home/Top8StoreSection.tsx
- src/contexts/GpsContext.tsx
- src/hooks/useStoreSearch.ts
- src/pages/store-map/StoreMapPage.tsx
- src/pages/store-search/StoreSearchPage.tsx
• DEFAULT_LOCATION 삭제 후 코드 리팩토링
• GPS 문제 / 새로고침 시 계속 기본값 기반 리스트 나오는 문제 해결
• 리스트 마진 삭제
• 마커 클릭 이벤트 수정
> fix: 지도 페이지 오류 해결 및 css 수정

- src/components/home/HeaderToCarouselSection.tsx
- src/hooks/useStoreSearch.ts
- src/pages/store-map/StoreMapPage.tsx
• 정확한 가게명 검색 => 해당 가맹점 상세 정보 페이지로 이동 (현위치 반경 20km 내에서 검색)
• 동/구/역 지역 기반 검색어 => 지도 페이지 이동 후 검색 실행
• 일반 키워드 검색어 => 지도 페이지 이동 후 검색 실행
> fix(SCRUM-201): 메인페이지 검색 오류 수정

- src/api/convenience.ts
- src/pages/convenience/NameRecommendationPage.tsx
> feat(SCRUM-148): 제품명 추천 API 연결

- src/hooks/useBottomSheet.ts
- src/pages/store-map/StoreMapPage.tsx
• 드래그 핸들에서 e.preventDefault()로 기본 동작을 막음
• touch-action: none으로 터치 동작을 제한
> fix: 모바일 드래그 핸들 동작 오류 수정

- src/api/auth.ts
- src/components/common/MenuBar.tsx
- src/hooks/useLoginStatus.ts
- src/hooks/useLogout.ts
• 로그인 api 호출 방식 수정 (GET -> POST)
• 메뉴바 로그인 했을 경우 -> 로그아웃 text로 변경
• 로그아웃 했을 경우 -> 화면 재렌더링
• 로그인 여부 판단 / 로그아웃 기능 -> hook으로 분리
> feat(SCRUM-203): 메뉴바 로그아웃 기능 추가

- index.html
- src/components/common/MenuBar.tsx
• 로그아웃 후 메인페이지로 이동
• 검색창 클릭 후 모바일 화면 크기 확대 막기 (user-scalable=0 옵션 추가)
> fix(SCRUM-231): 검색창 클릭 후 화면 크기 확대 이슈 해결

- src/pages/store-map/StoreMapPage.tsx
• 지도 중심 이동이 0.01 이하면 기존 마커에 새 마커를 누적(중복 제거)
• 0.01 초과면 기존 마커를 리셋
• fetchStores 호출 -> fetchStoresPromise로 변경
> feat(SCRUM-232): 지도페이지 이동 시 핀 누적 기능 추가

- src/components/Mypage/FeedbackBox.tsx
- src/pages/mypage/FeedbackPage.tsx
- src/pages/mypage/MyPage.tsx
- src/routes/index.tsx
• 의견 남기기 페이지 UI 구현
• 의견 남기기 페이지 기능 구현 (별점 / 의견 텍스트 입력 / 제출하기 로직 / 토스트 노출 및 이동)
• 의견 남기기 API 연동
> feat(SCRUM-183): 의견 남기기 페이지 UI 및 기능 구현

- src/api/mypage.ts
- src/components/Mypage/ChipGroup.tsx
- src/components/Mypage/MyConveniencePostItem.tsx
- src/components/Mypage/TabBar.tsx
- src/pages/mypage/MyPostsPage.tsx
- src/routes/index.tsx
• 게시글 tab UI 구현
• 내가 쓴 편의점 게시판 글 조회 API 연동
> feat(SCRUM-274): 내가 쓴 글 페이지 게시글 tab UI 구현

- src/components/Mypage/MyReviewItem.tsx
- src/pages/mypage/MyReviewsPage.tsx
• 가맹점 이름 클릭이벤트 구현 (가맹점 상세페이지로 이동)
• 리뷰 삭제 기능 구현
• storeName, storeId 필드 추가 후 기능 작동 확인
• 내가 쓴 리뷰 목록 무한스크롤 기능 구현 (page size = 10)
• totalCount 필드 BE 추가 후 '내가 쓴 리뷰 수' reviews.length => totalCount 변경
> feat(SCRUM-290): 내가 쓴 리뷰 목록 무한스크롤 기능 구현

- src/components/Mypage/MyLikePost.tsx
- src/pages/mypage/MyLikesPage.tsx
• 좋아요 페이지 UI 구현
• 글 클릭 시 해당 글 상세페이지로 이동 구현
• 좋아요 한 글 목록 무한스크롤 기능 구현
> feat(SCRUM-292): 좋아요 페이지 UI 및 기능 구현

- src/api/mypage.ts
- src/assets/svgs/community/reply-comment.svg
- src/components/Mypage/MyCommentPostList.tsx
- src/components/Mypage/MyLikePost.tsx
- src/pages/mypage/MyPostsPage.tsx
- src/pages/mypage/MyReviewsPage.tsx
- src/pages/mypage/MyScrapPage.tsx
• 내가 쓴 댓글 목록 UI 구현
• 내가 쓴 댓글 조회 API 연동
• 내가 쓴 리뷰 수 reviews.length => totalCount 변경
> feat(SCRUM-276): 내가 쓴 댓글 목록 UI 구현

- src/api/community.ts
- src/api/communityImg.ts
- src/components/Community/CategorySelector.tsx
- src/components/Community/CommentInput.tsx
- src/components/Community/CommentItem.tsx
- src/components/Community/ImageUploader.tsx
- src/components/Community/ReportButton.tsx
- src/components/StoreDetail/StoreDetailInfo.tsx
- src/components/StoreDetail/StoreDetailReview.tsx
- src/components/common/FloatingButton.tsx
- src/components/common/LoginRequiredBottomSheet.tsx
- src/components/layout/AppLayout.tsx
- src/pages/community/CommunityPostDetailPage.tsx
- src/pages/community/CommunityWritePage.tsx
- src/pages/convenience/AddConveniencePage.tsx
- 게시글 삭제, 수정
- 신고
- 게시글 이미지 업로드
- 로그인 모달 redirect 경로
> Feat/scrum 206/community report

- src/components/Community/CommentItem.tsx
- src/components/Community/ImageUploader.tsx
- src/components/Community/PostItem.tsx
- src/components/Community/ReportButton.tsx
- src/components/StoreDetail/ReportReviewButton.tsx
- src/components/StoreDetail/RequestEditButton.tsx
- src/components/StoreDetail/ReviewItem.tsx
- src/components/StoreReview/UploadImage.tsx
- src/components/common/WarningToast.tsx
- src/components/home/CarouselBanner.tsx
- src/pages/community/CommunityPage.tsx
- src/pages/community/CommunityPostDetailPage.tsx
- src/pages/community/CommunitySearchPage.tsx
- src/pages/community/CommunityWritePage.tsx
- src/pages/store-detail/StoreDetailPage.tsx
- src/pages/store-review/StoreReviewPage.tsx
> Feat/scrum 322/3rd sprint qa community

- src/components/Community/ImageUploader.tsx
- src/pages/community/CommunityPostDetailPage.tsx
- src/pages/community/CommunityWritePage.tsx
- src/pages/store-detail/StoreDetailPage.tsx
- 이미지 압축 로직 적용 후 이미지 사라지는 문제 해결
- 커뮤니티 헤더 수정
> Feat/scrum 328/final qa 2

- package-lock.json
- src/pages/auth/MyNeighborhoodPage.tsx
> feat(SCRUM-359):자주가는지역 동 추가

- src/components/Community/CommentInput.tsx
- src/components/Community/CommentItem.tsx
- src/hooks/useShare.ts
- src/pages/community/CommunityPostDetailPage.tsx
- src/pages/community/CommunityWritePage.tsx
- 상세페이지 신고하기 좋아요 정렬
- 엔터키 줄바꿈 문제 해결
- 공유하기 문제 해결
- 글 작성시 textarea 크기 조절 수정
> Fix/scrum 397/sprint4 qa community
